"""Optional[date] -> date AND ConfigDict

Revision ID: 52bd5d38a694
Revises: 872e8c799547
Create Date: 2026-05-14 11:47:59.612374

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "52bd5d38a694"
down_revision: Union[str, Sequence[str], None] = "872e8c799547"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
