"""Column(Date,Time - > String)

Revision ID: 872e8c799547
Revises: e22590a62656
Create Date: 2026-05-12 12:48:17.497323

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "872e8c799547"
down_revision: Union[str, Sequence[str], None] = "e22590a62656"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "bookings",
        "booking_date",
        existing_type=sa.DATE(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.alter_column(
        "bookings",
        "booking_time",
        existing_type=postgresql.TIME(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.alter_column(
        "calendar",
        "working_hours_start",
        existing_type=postgresql.TIME(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "calendar",
        "working_hours_end",
        existing_type=postgresql.TIME(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "calendar",
        "break_start",
        existing_type=postgresql.TIME(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.alter_column(
        "calendar",
        "break_end",
        existing_type=postgresql.TIME(),
        type_=sa.String(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "calendar",
        "break_end",
        existing_type=sa.String(),
        type_=postgresql.TIME(),
        existing_nullable=True,
    )
    op.alter_column(
        "calendar",
        "break_start",
        existing_type=sa.String(),
        type_=postgresql.TIME(),
        existing_nullable=True,
    )
    op.alter_column(
        "calendar",
        "working_hours_end",
        existing_type=sa.String(),
        type_=postgresql.TIME(),
        existing_nullable=False,
    )
    op.alter_column(
        "calendar",
        "working_hours_start",
        existing_type=sa.String(),
        type_=postgresql.TIME(),
        existing_nullable=False,
    )
    op.alter_column(
        "bookings",
        "booking_time",
        existing_type=sa.String(),
        type_=postgresql.TIME(),
        existing_nullable=True,
    )
    op.alter_column(
        "bookings",
        "booking_date",
        existing_type=sa.String(),
        type_=sa.DATE(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
